ALTER TABLE videos
ADD COLUMN view_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '視聴回数',
ADD COLUMN rating DECIMAL(3,2) NOT NULL DEFAULT 0.0 COMMENT '評価',
ADD COLUMN genre VARCHAR(255) NOT NULL COMMENT 'ジャンル',
ADD COLUMN posted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '投稿日時';
